buses/urls.py
from django.urls import include, path
from django.contrib import admin
from api import api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('api/', include(api.router.urls)),
    path('', include('busstops.urls')),
]


handler404 = 'busstops.views.not_found'

busstops/urls.py
from django.conf import settings
from django.conf.urls import static
from django.urls import include, path, re_path
from django.contrib import staticfiles
from django.contrib.sitemaps.views import sitemap, index
from bustimes.urls import urlpatterns as bustimes_views
from disruptions.urls import urlpatterns as disruptions_urls
from vehicles.urls import urlpatterns as vehicles_urls
from vosa.urls import urlpatterns as vosa_urls
from . import views

sitemaps = {
    'operators': views.OperatorSitemap,
    'services': views.ServiceSitemap,
}

urlpatterns = [
    path('', views.index),
    path('offline', views.offline),
    path('contact', views.contact),
    path('settings', views.settings),
    path('awin-transaction', views.awin_transaction),
    path('cookies', views.cookies),
    path('data', views.data),
    path('stops.json', views.stops),
    path('regions/<pk>', views.RegionDetailView.as_view(), name='region_detail'),
    path('places/<int:pk>', views.PlaceDetailView.as_view(), name='place_detail'),
    re_path(r'^(admin-)?areas/(?P<pk>\d+)', views.AdminAreaDetailView.as_view(), name='adminarea_detail'),
    path('districts/<int:pk>', views.DistrictDetailView.as_view(), name='district_detail'),
    re_path(r'^localities/(?P<pk>[ENen][Ss]?[0-9]+)', views.LocalityDetailView.as_view()),
    path('localities/<slug>', views.LocalityDetailView.as_view(), name='locality_detail'),
    path('stops/<pk>.json', views.stop_json),
    path('stops/<pk>.xml', views.stop_xml),
    path('stops/<pk>.txt', views.stop_gtfs),
    path('stops/<pk>', views.StopPointDetailView.as_view(), name='stoppoint_detail'),
    re_path(r'^operators/(?P<pk>[A-Z]+)$', views.OperatorDetailView.as_view()),
    path('operators/<slug>', views.OperatorDetailView.as_view(), name='operator_detail'),
    path('services/<int:service_id>.json', views.service_map_data),
    path('services/<slug>', views.ServiceDetailView.as_view(), name='service_detail'),
    path('sitemap.xml', index, {'sitemaps': sitemaps}),
    path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('search', views.search),
    path('journey', views.journey),
] + bustimes_views + disruptions_urls + vehicles_urls + vosa_urls


if settings.DEBUG and hasattr(staticfiles, 'views'):
    import debug_toolbar

    urlpatterns += [
        path('__debug__', include(debug_toolbar.urls)),
    ] + static.static('/', document_root=settings.STATIC_ROOT)

vosa/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('licences/<slug>', views.LicenceView.as_view(), name='licence_detail'),
    path('registrations/<path:slug>', views.RegistrationView.as_view(), name='registration_detail'),
    path('licences/<licence_number>/rss', views.LicenceFeed()),
    path('areas/<licence_number>/rss', views.AreaFeed())
]

disruptions/models.py
from django.db import models
from django.contrib.postgres.fields import DateTimeRangeField
from django.urls import reverse
from busstops.templatetags.date_range import date_range


class Situation(models.Model):
    source = models.ForeignKey('busstops.DataSource', models.CASCADE)
    situation_number = models.CharField(max_length=36, blank=True)
    reason = models.CharField(max_length=25, blank=True)
    summary = models.CharField(max_length=255, blank=True)
    text = models.TextField(blank=True)
    data = models.TextField(blank=True)
    created = models.DateTimeField()
    publication_window = DateTimeRangeField()
    current = models.BooleanField(default=True)

    def __str__(self):
        return self.summary

    def get_absolute_url(self):
        return reverse('situation', args=(self.id,))

    class Meta:
        unique_together = ('source', 'situation_number')


class Link(models.Model):
    url = models.URLField()
    situation = models.ForeignKey(Situation, models.CASCADE)

    def __str__(self):
        return self.url

    get_absolute_url = __str__


class ValidityPeriod(models.Model):
    situation = models.ForeignKey(Situation, models.CASCADE)
    period = DateTimeRangeField()

    def __str__(self):
        return date_range(self.period)


class Consequence(models.Model):
    situation = models.ForeignKey(Situation, models.CASCADE)
    stops = models.ManyToManyField('busstops.StopPoint', blank=True)
    services = models.ManyToManyField('busstops.Service', blank=True)
    operators = models.ManyToManyField('busstops.Operator', blank=True)
    text = models.TextField(blank=True)
    data = models.TextField(blank=True)

    def __str__(self):
        return self.text

    def get_absolute_url(self):
        service = self.services.first()
        if service:
            return service.get_absolute_url()
        return ''


class StopSuspension(models.Model):
    dates = DateTimeRangeField(null=True, blank=True)
    text = models.TextField(blank=True)
    stops = models.ManyToManyField('busstops.StopPoint')
    service = models.ForeignKey('busstops.Service', models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.text or str(self.dates)

busstops/forms.py
from django import forms
from django.core.exceptions import ValidationError
from antispam.honeypot.forms import HoneypotField
from antispam import akismet


class ContactForm(forms.Form):
    name = forms.CharField(label='Name')
    email = forms.EmailField(label='Email address')
    message = forms.CharField(label='Message', widget=forms.Textarea)
    spam_honeypot_field = HoneypotField()
    referrer = forms.CharField(label='Referrer', required=False,
                               widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super().__init__(*args, **kwargs)

    def clean(self):
        if self.request and self.is_valid() and 'seen_cookie_message' not in self.request.COOKIES and akismet.check(
            request=akismet.Request.from_django_request(self.request),
            comment=akismet.Comment(
                content=self.cleaned_data['message'],
                type='comment',
                author=akismet.Author(
                    name=self.cleaned_data['name'],
                    email=self.cleaned_data['email']
                )
            )
        ):
            raise ValidationError('Spam detected', code='spam-protection')


class SearchForm(forms.Form):
    q = forms.CharField(widget=forms.TextInput(attrs={"type": "search"}))

busstops/views.py
# coding=utf-8
"""View definitions."""
import json
import ciso8601
import requests
from ukpostcodeutils import validation
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.postgres.search import SearchQuery, SearchRank
from django.contrib.gis.geos import Point, Polygon
from django.contrib.gis.db.models.functions import Distance
from django.db.models import Q, Prefetch, F, Exists, OuterRef
from django.db.models.functions import Now
from django.http import HttpResponse, JsonResponse, Http404, HttpResponseBadRequest
from django.utils import timezone
from django.views.decorators.cache import cache_control
from django.views.generic.detail import DetailView
from django.core.paginator import Paginator
from django.contrib.sitemaps import Sitemap
from django.core.cache import cache
from django.core.mail import EmailMessage
from departures import live
from disruptions.models import Situation, Consequence, StopSuspension
from .utils import format_gbp, get_bounding_box
from .models import Region, StopPoint, AdminArea, Locality, District, Operator, Service, Place, ServiceColour
from .forms import ContactForm, SearchForm


prefetch_stop_services = Prefetch(
    'service_set', to_attr='current_services',
    queryset=Service.objects.filter(current=True).distinct('line_name', 'stops').order_by().defer('geometry')
)


def get_colours(services):
    colours = set(service.colour_id for service in services if service.colour_id)
    if colours:
        return ServiceColour.objects.filter(id__in=colours)


def index(request):
    """The home page with a list of regions"""
    return render(request, 'index.html', {
        'regions': True
    })


def not_found(request, exception):
    """Custom 404 handler view"""
    if request.resolver_match:
        context = {
            'exception': exception
        }
    else:
        context = None
    response = render(request, '404.html', context)
    response.status_code = 404
    return response


def offline(request):
    """Offline page (for service worker)"""
    return render(request, 'offline.html')


def settings(request):
    return render(request, 'settings.html')


def contact(request):
    """Contact page with form"""
    submitted = False
    if request.method == 'POST':
        form = ContactForm(request.POST, request=request)
        if form.is_valid():
            subject = form.cleaned_data['message'][:50].splitlines()[0]
            body = '{}\n\n{}'.format(form.cleaned_data['message'], form.cleaned_data['referrer'])
            message = EmailMessage(
                subject,
                body,
                '"{}" <contactform@bustimes.org>'.format(form.cleaned_data['name']),
                ['contact@bustimes.org'],
                reply_to=[form.cleaned_data['email']],
            )
            message.send()
            submitted = True
    else:
        referrer = request.META.get('HTTP_REFERER')
        form = ContactForm(initial={
            'referrer': referrer
        })
    return render(request, 'contact.html', {
        'form': form,
        'submitted': submitted
    })


def awin_transaction(request):
    json_string = request.POST.get('AwinTransactionPush') or request.body
    if not json_string:
        return HttpResponseBadRequest()
    data = json.loads(json_string)
    message = '\n'.join('%s: %s' % pair for pair in data.items())
    EmailMessage(
        '💷 {} on a {} transaction'.format(format_gbp(data['commission']), format_gbp(data['transactionAmount'])),
        message,
        '%s <%s>' % ('🚌⏰🤖', 'robot@bustimes.org'),
        ('contact@bustimes.org',)
    ).send()
    return HttpResponse()


def cookies(request):
    """Cookie policy"""
    return render(request, 'cookies.html')


def data(request):
    """Data sources"""
    return render(request, 'data.html')


def stops(request):
    """JSON endpoint accessed by the JavaScript map,
    listing the active StopPoints within a rectangle,
    in standard GeoJSON format
    """
    try:
        bounding_box = get_bounding_box(request)
    except KeyError:
        return HttpResponseBadRequest()

    results = StopPoint.objects.filter(
        latlong__within=bounding_box, active=True, service__current=True
    ).prefetch_related(
        prefetch_stop_services
    ).select_related('locality').defer('osm', 'locality__latlong').distinct()

    return JsonResponse({
        'type': 'FeatureCollection',
        'features': [{
            'type': 'Feature',
            'geometry': {
                'type': 'Point',
                'coordinates': tuple(stop.latlong)
            },
            'properties': {
                'name': stop.get_qualified_name(),
                'indicator': stop.indicator,
                'bearing': stop.get_heading(),
                'url': stop.get_absolute_url(),
                'services': stop.get_line_names()
            }
        } for stop in results]
    })


class UppercasePrimaryKeyMixin:
    """Normalises the primary key argument to uppercase"""
    def get_object(self, queryset=None):
        """Given a pk argument like 'ea' or 'sndr',
        convert it to 'EA' or 'SNDR',
        then otherwise behaves like ordinary get_object
        """
        primary_key = self.kwargs.get('pk')
        if primary_key is not None and '-' not in primary_key and not primary_key.isupper():
            self.kwargs['pk'] = primary_key.upper()
        return super().get_object(queryset)


class RegionDetailView(UppercasePrimaryKeyMixin, DetailView):
    """A single region and the administrative areas in it"""

    model = Region

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['areas'] = self.object.adminarea_set.exclude(name='')
        if len(context['areas']) == 1:
            context['districts'] = context['areas'][0].district_set.filter(locality__stoppoint__active=True).distinct()
            del context['areas']

        services = Service.objects.filter(current=True, operator=OuterRef('pk')).only('id')
        operators = self.object.operator_set.annotate(has_services=Exists(services))
        context['operators'] = operators.filter(Q(has_services=True))

        if len(context['operators']) == 1:
            context['services'] = sorted(context['operators'][0].service_set.filter(current=True).defer('geometry'),
                                         key=Service.get_order)

        return context


class PlaceDetailView(DetailView):
    model = Place
    queryset = model.objects.select_related('source')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['places'] = self.model.objects.filter(polygon__coveredby=self.object.polygon).exclude(id=self.object.id)

        if not context['places']:
            context['stops'] = StopPoint.objects.filter(latlong__coveredby=self.object.polygon)

        return context


class AdminAreaDetailView(DetailView):
    """A single administrative area,
    and the districts, localities (or stops) in it
    """

    model = AdminArea
    queryset = model.objects.select_related('region')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        stops = StopPoint.objects.filter(active=True)

        # Districts in this administrative area
        context['districts'] = self.object.district_set.filter(Exists(
            stops.filter(locality__district=OuterRef('pk'))
        ))

        # Districtless localities in this administrative area
        context['localities'] = self.object.locality_set.filter(
            Exists(stops.filter(locality=OuterRef('pk'))) | Exists(stops.filter(locality__parent=OuterRef('pk'))),
            district=None,
            parent=None
        ).defer('latlong')

        if not (context['localities'] or context['districts']):
            services = Service.objects.filter(current=True).defer('geometry', 'search_vector')
            services = services.filter(Exists(
                StopPoint.objects.filter(service=OuterRef('pk'), admin_area=self.object)
            ))
            context['services'] = sorted(services, key=Service.get_order)
            context['modes'] = {service.mode for service in context['services'] if service.mode}
        context['breadcrumb'] = [self.object.region]
        return context

    def render_to_response(self, context):
        if 'services' not in context and len(context['districts']) + len(context['localities']) == 1:
            if not context['localities']:
                return redirect(context['districts'][0])
            return redirect(context['localities'][0])
        return super().render_to_response(context)


class DistrictDetailView(DetailView):
    """A single district, and the localities in it"""

    model = District
    queryset = model.objects.select_related('admin_area', 'admin_area__region')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        stops = StopPoint.objects.filter(active=True)
        context['localities'] = self.object.locality_set.filter(
            Exists(stops.filter(locality=OuterRef('pk'))) | Exists(stops.filter(locality__parent=OuterRef('pk'))),
        ).defer('latlong')

        context['breadcrumb'] = [self.object.admin_area.region, self.object.admin_area]

        return context

    def render_to_response(self, context):
        if len(context['localities']) == 1:
            return redirect(context['localities'][0])
        return super().render_to_response(context)


class LocalityDetailView(UppercasePrimaryKeyMixin, DetailView):
    """A single locality, its children (if any), and the stops in it"""

    model = Locality
    queryset = model.objects.select_related(
        'admin_area', 'admin_area__region', 'district', 'parent'
    )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

busstops/templates/breadcrumb.html
{% if not regions %}
    <ol class="breadcrumb" itemscope itemtype="http://schema.org/BreadcrumbList">
        <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
            <a itemprop="item" href="/">
                <span itemprop="name">Home</span>
            </a>
            <meta itemprop="position" content="0">
        </li>
        {% for item in breadcrumb %}
            <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem">
                <a itemprop="item" href="{{ item.get_absolute_url }}">
                    <span itemprop="name">{% firstof item.get_line_name_and_brand item %}</span>
                </a>
                <meta itemprop="position" content="{{ forloop.counter }}">
            </li>
        {% endfor %}
    </ol>
{% endif %}

busstops/templates/cookies.html
{% extends 'page.html' %}

{% block title %}Cookies – bustimes.org{% endblock %}

{% block bodyclass %}narrow{% endblock %}

{% block content %}

<h1>Cookies</h1>

<p>‘Cookies’ are small text files stored on your computer when you use some websites, including this one.</p>

<p>For example, we use cookies to remember your place on <a href="/map">the map</a>, and to remember if you’ve opted into seeing personalised advertisements.</p>

<h2>Google Analytics cookies</h2>

<p>I use Google Analytics software to measure website traffic and performance, to help improve this website.</p>

<p>Google Analytics sets the following cookies:</p>

<table>
    <thead>
        <tr>
            <th scope="col">Name</th><th scope="col">Purpose</th><th scope="col">Expires after</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>_ga</td><td>Lets me know if you’ve visited the site before</td><td>2 years</td>
        </tr>
        <tr>
            <td>_gid</td><td>Lets me know if you’ve visited the site recently</td><td>24 hours</td>
        </tr>
        <tr>
            <td>_gat</td><td>Lets me control how frequently I record pageviews</td><td>10 minutes</td>
        </tr>
    </tbody>
</table>

<h2>Advertising cookies</h2>

<p>I display adverts, using Google AdSense, to fund the cost of operating this website.
Google and its partners use cookies ‘for frequency capping, aggregated ad reporting, and to combat fraud and abuse.’</p>

<p>
    <label><input type="checkbox" id="personalise-adverts"> Show personalised adverts</label>
</p>

<script>
(function () {
    var personaliseAds = document.getElementById('personalise-adverts');
    if (document.cookie.indexOf('personalise_ads=yes') !== -1) {
        personaliseAds.checked = true;
    } else {
        personaliseAds.checked = false;
    }

    function handlePersonaliseAds(event) {
        if (event.target.checked) {
            document.cookie = 'personalise_ads=yes; max-age=31536000; path=/';
        } else {
            document.cookie = 'personalise_ads=no; max-age=31536000; path=/';
        }
    }

    personaliseAds.addEventListener('click', handlePersonaliseAds);
})();
</script>

<o><a href="https://www.google.com/settings/ads">Google Ads Settings</a></o>

{% endblock %}

{% block ad %}{% endblock %}

busstops/templates/data.html
{% extends 'page.html' %}

{% block title %}Data sources – bustimes.org{% endblock %}

{% block bodyclass %}narrow{% endblock %}

{% block content %}

<h1>Data sources</h1>

<p>This website would be nothing without some useful third-party open data sources.<p>

<h2>Great Britain</h2>

<p>Data licensed under
<a href="http://www.nationalarchives.gov.uk/doc/open-government-licence/version/3/">version 3 of
the Open Government Licence</a>:</p>

<ul class="bulleted">
    <li><a href="https://data.gov.uk/dataset/nptg">The National Public Transport Gazetteer</a> (places)</li>
    <li><a href="https://data.gov.uk/dataset/naptan">The National Public Transport Access Node database</a> (bus stops)</li>
    <li><a href="http://www.travelinedata.org.uk/traveline-open-data/transport-operations/about-2/">The National Operator Codes database</a> (operators)</li>
    <li><a href="http://www.travelinedata.org.uk/traveline-open-data/traveline-national-dataset/">The Traveline National Dataset</a> (timetables)</li>
    <li><a href="https://data.gov.uk/dataset/9ea90ed8-de54-4274-92c6-272edd518bfb/traffic-commissioners-local-bus-service-registration">Traffic Commissioners: local bus service registration</a> (timetable changes)</li>
    <li><a href="http://www.transportapi.com/">Transport API</a> (live departure times)</li>
    <li><a href="https://tfl.gov.uk/info-for/open-data-users/">Transport for London open data</a> (live departure times)</li>
    <li><a href="https://opendata.transportforthenorth.com/">Transport for the North open data</a> (disruptions)</li>
</ul>

<p>Some information has been taken from <a href="https://www.bus-data.dft.gov.uk/">the bus open data digital service internet site</a>. While the Secretary of State for Transport strives to preserve the integrity and quality of information on the bus open data digital service internet site, the Secretary of State cannot warrant the accuracy or quality of the information on the site. bustimes.org does not have the endorsement, affiliation, support or approval of the Secretary of State.</p>

<p>Live vehicle tracking data comes from a number of different sources, including:</p>

<ul class="bulleted">
    <li><a href="http://rtl2.ods-live.co.uk/cms/">Reading Buses open data</a></li>
    <li><a href="https://tfe-opendata.readme.io/">Transport for Edinburgh open data</a></li>
    <li><a href="https://api-portal.tfwm.org.uk/">Transport for West Midlands API</a></li>
</ul>

<p>Information about vehicles (colours, registrations, fleet numbers, etc.) has been contributed by dozens of enthusiastic contributors.</p>

<p>Postcode search is powered by <a href="https://postcodes.io/about">Postcodes.io</a>.</p>

<h2>Northern Ireland</h2>

<ul class="bulleted">
    <li><a href="https://www.opendatani.gov.uk/organization/translink">Translink</a></li>
</ul>

<h2>Republic of Ireland</h2>

<ul class="bulleted">
    <li><a href="https://www.transportforireland.ie/transitData/PT_Data.html">Transport for Ireland</a></li>
    <li><a href="https://data.smartdublin.ie/dataset/real-time-passenger-information-rtpi-for-dublin-bus-bus-eireann-luas-and-irish-rail">Smart Dublin</a></li>
</ul>

<h2>Jersey</h2>

<ul class="bulleted">
    <li><a href="https://opendata.gov.je/dataset/live-bus-times">States of Jersey</a></li>
</ul>

{% endblock %}

busstops/templates/departures.html
{% if departures %}
<div class="aside">
    <h2>Next departures</h2>
    {% for item in departures %}
        {% ifchanged item.time.date %}
            {% if forloop.first or item.time.date and item.time.date != today %}
                {% if not forloop.first %}
                    </tbody>
                    </table>
                {% endif %}
                {% if item.time.date and item.time.date != today %}
                    <h3>{{ item.time|date:"l" }}</h3>
                {% endif %}
                <table>
                <tbody>
            {% endif %}
        {% endifchanged %}
        <tr>
            <td>
            {% if item.service.id %}
                <a href={{ item.service.get_absolute_url }}>{% firstof item.service.line_name item.service %}</a>
            {% elif item.service %}{{ item.service }}{% endif %}
            </td>
            <td>{{ item.destination }}</td>
            <td>
                {% if item.live %}
                    {{ item.live.time }}⚡
                {% else %}
                    {% firstof item.time.time item.time %}
                {% endif %}
            </td>
        </tr>
        {% if forloop.last %}
        </tbody>
        </table>
        {% endif %}
    {% endfor %}
    {% if live %}
        <p class="credit">⚡ denotes ‘live’ times guessed (sometimes badly) from buses’ actual locations</p>
    {% endif %}
</div>
{% endif %}

busstops/templates/edit_vehicle.html
{% extends 'page.html' %}

{% block title %}Edit details – {{ vehicle }} – Bus Times{% endblock %}

{% block bodyclass %}narrow{% endblock %}

{% block content %}

{% if submitted %}

    <h1>Thank you</h1>

    <p>I’ll update those details shortly</p>

{% else %}

    <h1>Edit vehicle details</h1>

    {% if pending_edits %}
        <p class="message">❗ There’s already a pending edit for this vehicle</p>
    {% endif %}

    <p>(You can also <a href="{{ vehicle.operator.get_absolute_url }}/vehicles/edit">edit several {{ vehicle.operator }} vehicles at once</a>)</p>

    <form action="/vehicles/{{ vehicle.id }}/edit" method="POST">
        {% if not form.fields.fleet_number.disabled %}
            <p>Code:<br>
            {{ vehicle.code }}</p>
        {% endif %}
        {{ form.as_p }}
        <input type="submit" value="Save changes" />
    </form>

{% endif %}

{% if previous %}
    <p class="previous"><a href="{{ previous.get_absolute_url }}/edit">&larr; {{ previous }}</a></p>
{% endif %}

{% if next %}
    <p class="next"><a href="{{ next.get_absolute_url }}/edit">{{ next }} &rarr;</a></p>
{% endif %}

{% endblock %}

{% block ad %}{% endblock %}

{% block foot %}
    {% load static %}
    <script src="{% static 'js/accessible-autocomplete/accessible-autocomplete.min.js' %}"></script>
    <script>
        window.addEventListener('DOMContentLoaded', function() {
            accessibleAutocomplete.enhanceSelectElement({
                selectElement: document.getElementById('id_vehicle_type')
            });
        });
    </script>
{% endblock %}

busstops/templates/index.html
{% extends 'page.html' %}

{% block bodyclass %}narrow{% endblock %}

{% block content %}

<p>
    <strong>bustimes.org</strong>
    is the unofficial home for bus, coach and ferry transport information
</p>

<div id="regions">

    <h2>Great Britain</h2>

    <ul>
        <li><a href="/regions/EA">East Anglia</a></li>
        <li><a href="/regions/EM">East Midlands</a></li>
        <li><a href="/regions/GB">Great Britain</a></li>
        <li><a href="/regions/L">London</a></li>
        <li><a href="/regions/NE">North East</a></li>
        <li><a href="/regions/NW">North West</a></li>
        <li><a href="/regions/S">Scotland</a></li>
        <li><a href="/regions/SE">South East</a></li>
        <li><a href="/regions/SW">South West</a></li>
        <li><a href="/regions/W">Wales</a></li>
        <li><a href="/regions/WM">West Midlands</a></li>
        <li><a href="/regions/Y">Yorkshire</a></li>
    </ul>

    <h2>Ireland</h2>

    <ul>
        <li><a href="/regions/CO">Connacht</a></li>
        <li><a href="/regions/LE">Leinster</a></li>
        <li><a href="/regions/MU">Munster</a></li>
        <li><a href="/regions/UL">Ulster</a></li>
    </ul>

    <!--[if gte IE 9]><!-->
        {% include 'regions.svg' %}
    <!--<![endif]-->
</div>

<ul>
    <li><a href="/regions/GG">Guernsey</a></li>
    <li><a href="/regions/JE">Jersey</a></li>
    <li><a href="/regions/IM">Isle of Man</a></li>
</ul>

{% load static %}
<script src="{% static 'js/frontpage.js' %}"></script>

{% endblock %}

busstops/templates/list.html
<ul class="long">
{% for item in list %}
    <li><a href="{{ item.get_absolute_url }}">{{ item }}</a></li>
{% endfor %}
</ul>

busstops/templates/modes.html
{% for mode in modes %}{% if forloop.first %}{{ mode.capitalize }}{% if forloop.last %} {{ noun }}{% endif %}{% elif forloop.last %} and {{ mode}} {{ noun }}{% else %}, {{ mode }}{% endif %}{% empty %}{{ noun.capitalize }}{% endfor %}

busstops/templates/situations.html
{% load urlise %}

{% for situation in situations %}
    <div class="situation">
        {% if situation.summary %}
            <div class="summary">
                {% if situation.reason %}
                    <div class="reason">
                        {% if situation.reason == 'roadClosed' %}Road closed{% elif situation.reason == 'routeDiversion' %}Diversion{% else %}{{ situation.reason|title }}{% endif %}
                    </div>
                {% endif %}
                <h2>{{ situation.summary }}</h2>
                {% if situation.validityperiod_set.all|length == 1%}
                    {{ situation.validityperiod_set.all.0 }}
                {% endif %}
            </div>
        {% endif %}
        {% if situation.text %}
            {{ situation.text|linebreaks }}
        {% endif %}
        {% for consequence in situation.consequences %}
            {% if consequence.text %}
                {{ consequence.text|linebreaks }}
            {% endif %}
        {% endfor %}
        {% for link in situation.link_set.all %}
            {{ link.url|urlise }}
        {% endfor %}
    </div>
{% endfor %}